import {Assets} from 'react-navigation-stack';

export default {
  SplashScreen: require('../Assets/splash.png'),
  // Login_bg: require('../Assets/backdrop_image.png'),
  BellGif: require('../Assets/dashboardNew/Bell.gif'),
  main_logo: require('../Assets/logo.png'),
  main_logo_withtext: require('../Assets/nbp_logo_new.png'),
  gif_tick: require('../../App/Assets/tick.gif'),
  etransactions: require('../../App/Assets/Icons/NewDrawer/etransactions.png'),
  Complaint: require('../../App/Assets/Icons/NewDrawer/ComplaintIcon.png'),
  onlineShopping: require('../../App/Assets/Icons/NewIcons/onlineshopping.png'),
  insurancepay: require('../../App/Assets/Icons/NewIcons/insurancepay.png'),
  Paypro: require('../../App/Assets/Icons/NewIcons/PayPro.png'),
  KuickPay: require('../../App/Assets/Icons/NewIcons/KuickPay.png'),
  rtpRequest: require('../Assets/Icons/NewIcons/rtprequest.png'),
  requestsforrequest: require('../Assets/Icons/NewIcons/requestforreturn.png'),
  themes: require('../Assets/Icons/NewDrawer/changeTheme.png'),
  downloadingGif: require('../Assets/downloadGif.gif'),
  newBottomErecipt: require('../Assets/bottomTaB/newBottomIcons/bottomerecipt.png'),
  newBottomInsurance: require('../Assets/bottomTaB/newBottomIcons/bottomInsurance.png'),
  newBottomInvest: require('../Assets/bottomTaB/newBottomIcons/bottomInsurance.png'),
  newBottomPayPro: require('../Assets/bottomTaB/newBottomIcons/bottomPaypro.png'),
  newBottomTheme: require('../Assets/bottomTaB/newBottomIcons/bottomTheme.png'),
  newBottomQR: require('../Assets/bottomTaB/newBottomIcons/bottomQR.png'),
  newBottomCer: require('../Assets/bottomTaB/newBottomIcons/bottomCertificate.png'),
  newBottomComplain: require('../Assets/bottomTaB/newBottomIcons/bottomComplain.png'),
  newBottomShop: require('../Assets/bottomTaB/newBottomIcons/bottomShop.png'),
  newBottomKuick: require('../Assets/bottomTaB/newBottomIcons/botomkuickPay.png'),
  newBottomRaast: require('../Assets/bottomTaB/newBottomIcons/bottomRaast.png'),

  //pinkTheme
  newBottomEreciptPinkTheme: require('../Assets/bottomTaB/newBottomIconsPink/bottomerecipt.png'),
  newBottomInsurancePinkTheme: require('../Assets/bottomTaB/newBottomIconsPink/bottomInsurance.png'),
  newBottomInvestPinkTheme: require('../Assets/bottomTaB/newBottomIconsPink/bottomInsurance.png'),
  newBottomPayProPinkTheme: require('../Assets/bottomTaB/newBottomIconsPink/bottomPaypro.png'),
  newBottomThemePinkTheme: require('../Assets/bottomTaB/newBottomIconsPink/bottomTheme.png'),
  newBottomQRPinkTheme: require('../Assets/bottomTaB/newBottomIconsPink/bottomQR.png'),
  newBottomCerPinkTheme: require('../Assets/bottomTaB/newBottomIconsPink/bottomCertificate.png'),
  newBottomComplainPinkTheme: require('../Assets/bottomTaB/newBottomIconsPink/bottomComplain.png'),
  newBottomShopPinkTheme: require('../Assets/bottomTaB/newBottomIconsPink/bottomShop.png'),
  newBottomKuickPinkTheme: require('../Assets/bottomTaB/newBottomIconsPink/botomkuickPay.png'),
  newBottomRaastPinkTheme: require('../Assets/bottomTaB/newBottomIconsPink/bottomRaast.png'),
  //indigoTheme
  newBottomEreciptIndigoTheme: require('../Assets/bottomTaB/newBottomIconsIndigo/bottomerecipt.png'),
  newBottomInsuranceIndigoTheme: require('../Assets/bottomTaB/newBottomIconsIndigo/bottomInsurance.png'),
  newBottomInvestIndigoTheme: require('../Assets/bottomTaB/newBottomIconsIndigo/bottomInsurance.png'),
  newBottomPayProIndigoTheme: require('../Assets/bottomTaB/newBottomIconsIndigo/bottomPaypro.png'),
  newBottomThemeIndigoTheme: require('../Assets/bottomTaB/newBottomIconsIndigo/bottomTheme.png'),
  newBottomQRIndigoTheme: require('../Assets/bottomTaB/newBottomIconsIndigo/bottomQR.png'),
  newBottomCerIndigoTheme: require('../Assets/bottomTaB/newBottomIconsIndigo/bottomCertificate.png'),
  newBottomComplainIndigoTheme: require('../Assets/bottomTaB/newBottomIconsIndigo/bottomComplain.png'),
  newBottomShopIndigoTheme: require('../Assets/bottomTaB/newBottomIconsIndigo/bottomShop.png'),
  newBottomKuickIndigoTheme: require('../Assets/bottomTaB/newBottomIconsIndigo/botomkuickPay.png'),
  newBottomRaastIndigoTheme: require('../Assets/bottomTaB/newBottomIconsIndigo/bottomRaast.png'),
  //OrangeTheme
  newBottomEreciptOrangeTheme: require('../Assets/bottomTaB/newBottomIconsOrange/bottomerecipt.png'),
  newBottomInsuranceOrangeTheme: require('../Assets/bottomTaB/newBottomIconsOrange/bottomInsurance.png'),
  newBottomInvestOrangeTheme: require('../Assets/bottomTaB/newBottomIconsOrange/bottomInsurance.png'),
  newBottomPayProOrangeTheme: require('../Assets/bottomTaB/newBottomIconsOrange/bottomPaypro.png'),
  newBottomThemeOrangeTheme: require('../Assets/bottomTaB/newBottomIconsOrange/bottomTheme.png'),
  newBottomQROrangeTheme: require('../Assets/bottomTaB/newBottomIconsOrange/bottomQR.png'),
  newBottomCerOrangeTheme: require('../Assets/bottomTaB/newBottomIconsOrange/bottomCertificate.png'),
  newBottomComplainOrangeTheme: require('../Assets/bottomTaB/newBottomIconsOrange/bottomComplain.png'),
  newBottomShopOrangeTheme: require('../Assets/bottomTaB/newBottomIconsOrange/bottomShop.png'),
  newBottomKuickOrangeTheme: require('../Assets/bottomTaB/newBottomIconsOrange/botomkuickPay.png'),
  newBottomRaastOrangeTheme: require('../Assets/bottomTaB/newBottomIconsOrange/bottomRaast.png'),

  //Dashboard Assets
  // banner1: require('../Assets/Dashboard_Assets/screen1.jpg'),
  // banner2: require('../Assets/Dashboard_Assets/screen2.jpg'),
  // banner3: require('../Assets/Dashboard_Assets/screen3.jpg'),
  // banner4: require('../Assets/Dashboard_Assets/screen4.png'),
  // floodDonateUs: require('../Assets/Dashboard_Assets/DonateUs.png'),
  menuDash: require('../Assets/Dashboard_Assets/Menu.png'),
  //loader
  nbp_loader: require('../Assets/nbp_loader.gif'),
  touchIdNew: require('../Assets/TouchId.png'),
  faceIdNew: require('../Assets/FaceIDNew.png'),
  //header_icons
  // header_icon_registeration: require('../Assets/icon/registration_head_icon.png'),
  // header_icon_login: require('../Assets/icon/device-verification.png'),

  ////Login screen////
  locatorIcon: require('../Assets/atm.png'),
  touchIdBtn: require('../Assets/Login_Assets/TouchIdConfig.png'),
  faceIdBtn: require('../Assets/Login_Assets/faceIdConfig.png'),
  contactUsBtn: require('../Assets/Login_Assets/contactUs.png'),
  FaqsBtn: require('../Assets/Login_Assets/btn_faqs_normal.png'),
  // investmentBtn: require('../Assets/Login_Assets/btn_investment_login_normal.png'),
  // investment: require('../Assets/Login_Assets/inv.png'),
  // investment2: require('../Assets/investmenttracefinal01.png'),
  // TncBtn: require('../Assets/Login_Assets/btn_t_c_normal.png'),
  // touchConfig: require('../Assets/Login_Assets/configure.png'),
  AtmLocater: require('../Assets/Login_Assets/locateUs.png'),
  // signupBtn: require('../Assets/Login_Assets/btn_signin_normal.png'),

  //otherPaymentsImages
  // otherSubHeader: require('../Assets/logo.png'),
  // otherOne: require('../Assets/logo.png'),
  // otherTwo: require('../Assets/logo.png'),
  // otherThree: require('../Assets/logo.png'),
  // otherFour: require('../Assets/logo.png'),
  // otherFive: require('../Assets/logo.png'),
  // otherSix: require('../Assets/logo.png'),
  // otherSeven: require('../Assets/logo.png'),
  // otherEight: require('../Assets/logo.png'),
  // otherNine: require('../Assets/logo.png'),
  // otherTen: require('../Assets/logo.png'),
  // otherEleven: require('../Assets/logo.png'),

  //myAccounts
  // myAccountSubHeader: require('../Assets/logo.png'),
  // myAccountOne: require('../Assets/logo.png'),
  // myAccountTwo: require('../Assets/logo.png'),
  // myAccountThree: require('../Assets/logo.png'),

  //unionPayCardMgmt
  // unionPayCardMgmtSubHeader: require('../Assets/logo.png'),
  // unionPayCardMgmtOne: require('../Assets/logo.png'),
  // unionPayCardMgmtTwo: require('../Assets/logo.png'),

  // //mobileBillPmnt
  // mobileBillPmntSubHeader: require('../Assets/logo.png'),

  // // utilityBillPmt
  // utilityBillSubHeader: require('../Assets/logo.png'),

  // unionPayCardMgmt

  // benefPmt
  // benefPmtSubHeader: require('../Assets/logo.png'),

  // // benefMgmt
  // benefMgmtSubHeader: require('../Assets/logo.png'),
  // benefMgmtSearch: require('../Assets/search.png'),
  // benefMgmtSearchBackground: require('../Assets/searchBackgroundImage.png'),

  // unionPmt
  // unionPmtSubHeader: require('../Assets/logo.png'),
  // unionPmtOne: require('../Assets/logo.png'),
  // unionPmtTwo: require('../Assets/logo.png'),

  // transfers
  // transferSubHeader: require('../Assets/logo.png'),
  // transferOne: require('../Assets/logo.png'),
  // transferTwo: require('../Assets/logo.png'),
  // transferThree: require('../Assets/logo.png'),
  isAccount: require('../Assets/image_cheque_book.png'),

  //debit card managment icons

  // cardissuance: require('../Assets/AppIcons/card_activation.png'),
  // cardActivationTab: require('../Assets/DebitCard/activation.png'),
  // cardStatusTab: require('../Assets/DebitCard/status.png'),
  // cardIssuanceTab: require('../Assets/DebitCard/issuance.png'),
  // cardPinTab: require('../Assets/DebitCard/pin.png'),
  // cardForgotPinTab: require('../Assets/DebitCard/forgotPin.png'),
  // cardActivationHeader: require('../Assets/DebitCard/activationHeader.png'),
  // cardForgotPinHeader: require('../Assets/DebitCard/forgotPinHeader.png'),
  // cardIssuanceHeader: require('../Assets/DebitCard/issuanceHeader.png'),
  // cardPinHeader: require('../Assets/DebitCard/pinHeader.png'),
  // cardStatusHeader: require('../Assets/DebitCard/statusHeader.png'),
  payPak: require('../Assets/DebitCard/cardTypePayPak.png'),
  unionPay: require('../Assets/DebitCard/cardTypeVisa.png'),
  cardBack: require('../Assets/DebitCard/CardBG.png'),
  unionPayBG: require('../Assets/DebitCard/UnionPay.png'),
  payPakBG: require('../Assets/DebitCard/PayPak.png'),
  checkIBAN: require('../Assets/cheaquIBAN.jpeg'),
  accountOpening: require('../Assets/Login_Assets/openAcc.png'),
  // debitBanner: require('../Assets/DebitCard/DebitCardBanner.png'),
  // debitBannerSec: require('../Assets/DebitCard/DebitCardSecondryDebit.png'),
  // employeeBanner: require('../Assets/employeeBanner.png'),
  // newEmployeeBanner: require('../Assets/NewEmpBanner.png'),
  // floodReliefBanner: require('../Assets/FloodReliefFundLanding.png'),
  // Singallogo: require('../Assets/Singallogo.png'),
  BackBlack: require('../Assets/Icons/NewIcons/backBlack.png'),
  //new Login Assests
  loginAccDet: require('../Assets/Login_Assets/accDetails.png'),
  // New Dashboardd Assets
  dashboardbenefManag: require('../Assets/dashboardNew/benefManag.png'),
  dashboardbenefPay: require('../Assets/dashboardNew/benefPay.png'),
  dashboardContributeFlood: require('../Assets/dashboardNew/ContributeFlood.png'),
  dashboarddebitCard: require('../Assets/dashboardNew/debitCard.png'),
  dashboardfundTransfer: require('../Assets/dashboardNew/fundTransfer.png'),
  dashboardmobileTopUp: require('../Assets/dashboardNew/mobileTopUp.png'),
  dashboardmyAccount: require('../Assets/dashboardNew/myAccount.png'),
  dashboardoneBill: require('../Assets/dashboardNew/oneBill.png'),
  dashboardutilityBillPay: require('../Assets/dashboardNew/utilityBillPay.png'),
  dashboardInvestment: require('../Assets/dashboardNew/Invest.png'),
  dashboardDonation: require('../Assets/dashboardNew/Donation.png'),
  dashboardInternet: require('../Assets/dashboardNew/InternetPaymets.png'),
  dashboardEducation: require('../Assets/dashboardNew/EducationFees.png'),
  // dashboardraastPayments: require('../Assets/dashboardNew/raastPayments.png'),
  dashboarDarkdutilityBillPay: require('../Assets/dashboardNew/DashboardDarkMode/utilityBillPay.png'),
  dashboardDarkbenefManag: require('../Assets/dashboardNew/DashboardDarkMode/benefManag.png'),
  dashboardDarkbenefPay: require('../Assets/dashboardNew/DashboardDarkMode/benefPay.png'),
  dashboardDarkdebitCard: require('../Assets/dashboardNew/DashboardDarkMode/debitCard.png'),
  dashboardDarkfundTransfer: require('../Assets/dashboardNew/DashboardDarkMode/fundTransfer.png'),
  dashboardDarkmobileTopUp: require('../Assets/dashboardNew/DashboardDarkMode/mobileTopUp.png'),
  dashboardDarkmyAccount: require('../Assets/dashboardNew/DashboardDarkMode/myAccount.png'),
  dashboardDarkoneBill: require('../Assets/dashboardNew/DashboardDarkMode/oneBill.png'),
  dashboardDarkutilityBillPay: require('../Assets/dashboardNew/DashboardDarkMode/utilityBillPay.png'),
  dashboardDarkfbrTax: require('../Assets/dashboardNew/DashboardDarkMode/fbrTax.png'),

  dashboarDarkdDonation: require('../Assets/dashboardNew/DashboardDarkMode/Donation.png'),
  dashboardPinkDonation: require('../Assets/dashboardNew/DashboardPinkMode/Donation.png'),
  dashboardIndigoDonation: require('../Assets/dashboardNew/DashboardIndigoMode/Donation.png'),
  dashboardOrangeDonation: require('../Assets/dashboardNew/DashboardOrangemode/Donation.png'),
  dashboardDarkInternet: require('../Assets/dashboardNew/DashboardDarkMode/OnlinePayments.png'),
  dashboardPinkInternet: require('../Assets/dashboardNew/DashboardPinkMode/OnlinePayments.png'),
  dashboardIndigoInternet: require('../Assets/dashboardNew/DashboardIndigoMode/OnlinePayments.png'),
  dashboardOrangeInternet: require('../Assets/dashboardNew/DashboardOrangemode/OnlinePayments.png'),
  dashboardDarkEducation: require('../Assets/dashboardNew/DashboardDarkMode/EducationFees.png'),
  dashboardPinkEducation: require('../Assets/dashboardNew/DashboardPinkMode/EducationFees.png'),
  dashboardIndigoEducation: require('../Assets/dashboardNew/DashboardIndigoMode/EducationFees.png'),
  dashboardOrangeEducation: require('../Assets/dashboardNew/DashboardOrangemode/EducationFee.png'),
  dashboardDarkInvestment: require('../Assets/dashboardNew/DashboardDarkMode/Invest.png'),
  dashboardPinkInvestment: require('../Assets/dashboardNew/DashboardPinkMode/Invest.png'),
  dashboardIndigoInvestment: require('../Assets/dashboardNew/DashboardIndigoMode/Invest.png'),
  dashboardOrangeInvestment: require('../Assets/dashboardNew/DashboardOrangemode/Invest.png'),

  //dark Mode Dashboard icon

  // dashboardraastPayments: require('../Assets/dashboardNew/raastPayments.png'),
  dashboardOrangedutilityBillPay: require('../Assets/dashboardNew/DashboardOrangemode/utilityBillPay.png'),
  dashboardOrangebenefManag: require('../Assets/dashboardNew/DashboardOrangemode/benefManag.png'),
  dashboardOrangebenefPay: require('../Assets/dashboardNew/DashboardOrangemode/benefPay.png'),
  dashboardOrangedebitCard: require('../Assets/dashboardNew/DashboardOrangemode/debitCard.png'),
  dashboardOrangefundTransfer: require('../Assets/dashboardNew/DashboardOrangemode/fundTransfer.png'),
  dashboardOrangemobileTopUp: require('../Assets/dashboardNew/DashboardOrangemode/mobileTopUp.png'),
  dashboardOrangemyAccount: require('../Assets/dashboardNew/DashboardOrangemode/myAccount.png'),
  dashboardOrangeoneBill: require('../Assets/dashboardNew/DashboardOrangemode/oneBill.png'),
  dashboardOrangeutilityBillPay: require('../Assets/dashboardNew/DashboardOrangemode/utilityBillPay.png'),
  dashboardOrangefbrTax: require('../Assets/dashboardNew/DashboardOrangemode/fbrTax.png'),

  dashboardPinkdutilityBillPay: require('../Assets/dashboardNew/DashboardPinkMode/utilityBillPay.png'),
  dashboardPinkbenefManag: require('../Assets/dashboardNew/DashboardPinkMode/benefManag.png'),
  dashboardPinkbenefPay: require('../Assets/dashboardNew/DashboardPinkMode/benefPay.png'),
  dashboardPinkdebitCard: require('../Assets/dashboardNew/DashboardPinkMode/debitCard.png'),
  dashboardPinkfundTransfer: require('../Assets/dashboardNew/DashboardPinkMode/fundTransfer.png'),
  dashboardPinkmobileTopUp: require('../Assets/dashboardNew/DashboardPinkMode/mobileTopUp.png'),
  dashboardPinkmyAccount: require('../Assets/dashboardNew/DashboardPinkMode/myAccount.png'),
  dashboardPinkoneBill: require('../Assets/dashboardNew/DashboardPinkMode/oneBill.png'),
  dashboardPinkutilityBillPay: require('../Assets/dashboardNew/DashboardPinkMode/utilityBillPay.png'),
  dashboardPinkfbrTax: require('../Assets/dashboardNew/DashboardPinkMode/fbrTax.png'),

  dashboardIndigodutilityBillPay: require('../Assets/dashboardNew/DashboardIndigoMode/utilityBillPay.png'),
  dashboardIndigobenefManag: require('../Assets/dashboardNew/DashboardIndigoMode/benefManag.png'),
  dashboardIndigobenefPay: require('../Assets/dashboardNew/DashboardIndigoMode/benefPay.png'),
  dashboardIndigodebitCard: require('../Assets/dashboardNew/DashboardIndigoMode/debitCard.png'),
  dashboardIndigofundTransfer: require('../Assets/dashboardNew/DashboardIndigoMode/fundTransfer.png'),
  dashboardIndigomobileTopUp: require('../Assets/dashboardNew/DashboardIndigoMode/mobileTopUp.png'),
  dashboardIndigomyAccount: require('../Assets/dashboardNew/DashboardIndigoMode/myAccount.png'),
  dashboardIndigooneBill: require('../Assets/dashboardNew/DashboardIndigoMode/oneBill.png'),
  dashboardIndigoutilityBillPay: require('../Assets/dashboardNew/DashboardIndigoMode/utilityBillPay.png'),
  dashboardIndigofbrTax: require('../Assets/dashboardNew/DashboardIndigoMode/fbrTax.png'),

  otpLogoDefault: require('../Assets/otpLogo.png'),
  otpLogoDark: require('../Assets/dashboardNew/DashboardDarkMode/otpdark.png'),
  otpLogoPink: require('../Assets/dashboardNew/DashboardPinkMode/mobileTopUp.png'),
  otpLogoIndigo: require('../Assets/dashboardNew/DashboardIndigoMode/otpdark.png'),
  otpLogoOrange: require('../Assets/dashboardNew/DashboardOrangemode/otpdark.png'),

  //dark Mode Dashboard icon
  newReferalBanner: require('../Assets/generalBannerEmp.png'),
  // androidShareEMP: require('../Assets/AndroidSHare2.png'),
  // iosShareEMP: require('../Assets/IOSShare2.png'),
  bottomBill: require('../Assets/bottomTaB/bottomBill.png'),
  bottomCard: require('../Assets/bottomTaB/bottomCard.png'),
  bottomQR: require('../Assets/bottomTaB/bottomQR.png'),
  bottomTop: require('../Assets/bottomTaB/bottomTop.png'),
  bottomTransfer: require('../Assets/bottomTaB/bottomTransfer.png'),
  bottomRaastQr: require('../Assets/bottomTaB/raastQRShare.png'),
  bottomInvest: require('../Assets/bottomTaB/bottomInvest.png'),
  bottomSport: require('../Assets/bottomTaB/bottomSport.png'),
  bottomDonation: require('../Assets/bottomTaB/bottomDonation.png'),
  galleryQR: require('../Assets/galleryQR.png'),
  receiveQR: require('../Assets/receiveQR.png'),
  androidShareDash: require('../Assets/Icons/NewIcons/android2.png'),
  iosShareDash: require('../Assets/Icons/NewIcons/iosShareDash.png'),
  loginQr: require('../Assets/Login_Assets/Qr.png'),
  raastLoginQr: require('../Assets/Login_Assets/RaastLogin.png'),

  resendOtpIcon: require('../Assets/Login_Assets/resendOtp.png'),
  touchIdGreen: require('../Assets/Login_Assets/touchIDGreen.png'),
  faceIDGreen: require('../Assets/Login_Assets/faceIDGreen.png'),
  alertIcon: require('../Assets/alertIcon.png'),
  successAlert: require('../Assets/successAlert.png'),
  failAlert: require('../Assets/failed.png'),
  removeAlert: require('../Assets/removeAlert.png'),
  alertIconGreen: require('../Assets/Icons/NewIcons/alertIconGreen.png'),
  raastQr: require('../Assets/Icons/NewIcons/raastQr.png'),
  raastManag: require('../Assets/Icons/NewIcons/raastManag.png'),
  raastViaId: require('../Assets/Icons/NewIcons/raastViaId.png'),
  closeBtn: require('../Assets/Icons/NewIcons/closeBtn.png'),
  logoWithText: require('../Assets/Icons/logoWithText.png'),
  logoWithTextDark: require('../Assets/Icons/logoWithTextDark.png'),
  addAccount: require('../Assets/Icons/NewIcons/addAccount.png'),
  manageAccount: require('../Assets/Icons/NewIcons/accountManage.png'),
  shareRec: require('../Assets/Icons/NewIcons/ShareRecipt.png'),
  DownloadReciept: require('../Assets/Icons/NewIcons/DownloadReciept.png'),
  closeRec: require('../Assets/Icons/NewIcons/closeGrey.png'),
  androidShareEtrans: require('../Assets/Icons/NewIcons/androidShareEtrans.png'),
  addVirtualCard: require('../Assets/Icons/NewIcons/addVirtualCard.png'),
  androidIconWhiteShare: require('../Assets/Icons/NewIcons/androidShareWhite.png'),
  iosShareWhite: require('../Assets/Icons/NewIcons/iosShareWhite.png'),
  virtualCard: require('../Assets/Icons/NewIcons/virtualCard.png'),
  debitCard: require('../Assets/Icons/NewDrawer/unionmanage.png'),
  raastBlack: require('../Assets/Icons/NewDrawer/raast.png'),
  fbrTax: require('../Assets/dashboardNew/fbrTax.png'),
  blankCard: require('../Assets/blankCard.png'),
  blankCardBlack: require('../Assets/blankCardBlack.png'),
  noBenef: require('../Assets/noBenef.png'),
  searchBenef: require('../Assets/Icons/NewIcons/searchBenef.png'),
  noResultFound: require('../Assets/Icons/NewIcons/noResultFound.png'),
  outGoing: require('../Assets/Icons/NewIcons/outgoing.png'),
  income: require('../Assets/Icons/NewIcons/income.png'),
  outgoingGreen: require('../Assets/Icons/NewIcons/outgoingGreen.png'),
  serviceNotAvailabe: require('../Assets/servicesNotAvailable.png'),
  raast2nd: require('../Assets/Icons/NewDrawer/Ibftt.png'),
  cameraLineicon: require('../Assets/Icons/NewDrawer/cameraIcon.png'),
  galleryLineIcon: require('../Assets/Icons/NewDrawer/galleryIcon.png'),
  certificatesIcon: require('../Assets/Icons/NewDrawer/certificates.png'),
  powerdbyUnionpay: require('../Assets/poweredbyunionpay.png'),
  Investment: require('../Assets/Icons/NewDrawer/Investment.png'),
  Mobilink: require('../Assets/MobileTopUp/Jazz.png'),
  Telenor: require('../Assets/MobileTopUp/TelenorMicrofinanceBank.png'),
  Ufone: require('../Assets/MobileTopUp/Ufone.png'),
  Zong: require('../Assets/MobileTopUp/ZOng.png'),
  QRaaast: require('../Assets/bottomTaB/QRaaast.png'),
};
