export const darkTheme = {
  dashboardIconText: 'white',

  beneficiaryList: '#272727',
  beneficiaryListPressed: '#3e3e3e',
  dashboardBalancehider: '#121212',
  appHeaderColor: '#272727',
  dashboardBottomTabTex: 'white',
  alertThemeTextColor: 'white',
  isPinkTheme: false,
  isIndigoTheme: false,
  isOrangeTheme: false,
  isDarkTheme: true,
  isLightTheme: false,
  newViewBackGround: '#009951',
  headerBackGroundColor: '#272727',
  headerArrowColor: '#AFAFAF',
  mainBackGroundColor: '#121212',
  textfieldBackgroundColor: '#272727',
  alertBackGroundColor: '#272727',
  transferReciptDownlaodBtn: 'white',
  smoothCodePinInputBackground: '#272727',

  textFieldCursor: 'white',
  textFieldText: 'white',
  mainTextColors: 'white',
  loginBottomNav: '#272727',
  tabNavigateBackground: '#272727',
  tabNavigateTextBackground: 'white',
  tabNavigateLeftIcon: 'white',
  tabNavigateRightIcon: 'white',
  generalIcon: 'white',
  childContainer: '#3e3e3e',
  subContainer: '#272727',
  tabNavigateonPress: '#3d464d',
  tabBarColor: '#3e3e3e',
  dashboardHeaderBack: '#121212',
  dashboardLogoutBtn: '#005728',
  dashboardSubContainerBack: '#272727',
  dashboardChildContainerBack: '#494d50',
  dashboardBackGroundColor: '#121212',

  textFieldBorderColor: '#272727',
  drawerBackGround: '#272727',
  silver: 'silver',
  red: 'red',
  whiteColor: 'white',
  primary_green: '#009951',
  grey: 'grey',
  lightGrey: 'lightgrey',
  icon_color: '#009951',
  icon_under_coolor: '#009951',
  header_background: 'white',
  header_left_btn_color: '#009951',
  overall_view_color: '#009951',
  //Dashboard
  dash_icon_color: '#009951',
  //smooth input view
  smoothinpout_color: '#009951',
  //alert icon_color
  alet_icon: '#ffe135',
  noteRed: 'red',
  blackColor: 'black',
  themeGreyColor: '#b5b5b5',
  smoothCodeInputTextColor: 'grey',
  orange: 'orange',
  backgroundColor: '#121212',
  PrimaryBlue: '#0d1821',
  borderColor: '#cfd1d3',
  darkGreen: '#005c31',
  secondaryColor: '#0d1821',
  BtnBackground: '#009951',
  secondaryLight: '#252f37',
  secondaryLighter: '#3d464d',
  dashboardIconBack: '#272727',
  dashboardBottomTabView: '#272727',
  dashboardBottomIcon: 'white',
  modalComponentHeader: '#009951',
  modalBackGround: '#272727',
  DarkGreen: '#005728',
  greyInfoShow: '#eceded',
  themeGrey: '#cfd1d3',
  labelGrey: '#9ea3a6',
  lightThemeGreen: '#ccebdc',
  lightRedColor: '#ffe6eb',
  redColor: '#ff4d72',
  pink: '#ff6686',
  seaGreen: '#009951',
  yellow: 'yellow',
};

export const lightTheme = {
  dashboardIconText: 'black',

  beneficiaryList: 'white',
  beneficiaryListPressed: 'grey',
  dashboardBalancehider: '#3d464d',
  isPinkTheme: false,
  isIndigoTheme: false,
  isOrangeTheme: false,
  isDarkTheme: false,
  isLightTheme: true,
  dashboardBottomTabTex: '#0d1821',
  alertThemeTextColor: '#009951',
  smoothCodePinInputBackground: 'white',
  newViewBackGround: '#009951',

  appHeaderColor: '#009951',

  //header
  headerBackGroundColor: '#009951',
  headerArrowColor: '#005728',
  //main
  mainBackGroundColor: '#f3f4f4',
  //textFiled
  textfieldBackgroundColor: 'white',
  textFieldCursor: '#009951',
  textFieldText: 'black',
  //custom Text Color
  mainTextColors: 'black',
  loginBottomNav: '#0d1821',
  //Tab Navigate
  tabNavigateBackground: 'white',
  transferReciptDownlaodBtn: '#0d1821',

  tabNavigateTextBackground: 'black',
  tabNavigateLeftIcon: 'black',
  tabNavigateRightIcon: 'black',
  tabNavigateonPress: 'white',
  tabBarColor: 'lightgrey',
  //dashboard
  dashboardHeaderBack: '#009951',
  dashboardLogoutBtn: '#005728',
  dashboardSubContainerBack: '#0d1821',
  dashboardChildContainerBack: '#252f37',
  dashboardBottomTabView: 'white',
  dashboardBottomIcon: '#0d1821',
  dashboardBackGroundColor: 'white',
  textFieldBorderColor: '#cfd1d3',

  modalComponentHeader: '#009951',
  modalBackGround: 'white',
  alertBackGroundColor: 'white',

  BtnBackground: '#009951',
  subContainer: 'white',
  silver: 'silver',
  red: 'red',
  whiteColor: 'white',
  primary_green: '#009951',
  grey: 'grey',
  lightGrey: 'lightgrey',
  icon_color: '#009951',
  icon_under_coolor: '#009951',
  header_background: 'white',
  header_left_btn_color: '#009951',
  overall_view_color: '#009951',
  //Dashboard
  dash_icon_color: '#009951',
  //smooth input view
  smoothinpout_color: '#009951',
  //alert icon_color
  generalIcon: 'black',
  childContainer: '#eceded',
  alet_icon: '#ffe135',
  noteRed: 'red',
  blackColor: 'black',
  themeGreyColor: '#b5b5b5',
  smoothCodeInputTextColor: 'grey',
  orange: 'orange',
  backgroundColor: '#f3f4f4',
  PrimaryBlue: '#0d1821',
  borderColor: '#cfd1d3',
  darkGreen: '#005c31',
  secondaryColor: '#0d1821',
  drawerBackGround: '#f3f4f4',
  secondaryLight: '#252f37',
  secondaryLighter: '#3d464d',
  dashboardIconBack: '#f1f1f2',
  DarkGreen: '#005728',
  greyInfoShow: '#eceded',
  themeGrey: '#cfd1d3',
  labelGrey: '#9ea3a6',
  lightThemeGreen: '#ccebdc',
  lightRedColor: '#ffe6eb',
  redColor: '#ff4d72',
  pink: '#ff6686',
  seaGreen: '#009951',
  yellow: 'yellow',
};

export const pinkTheme = {
  beneficiaryList: 'white',
  beneficiaryListPressed: 'grey',
  dashboardBalancehider: '#FDBDD0',
  isPinkTheme: true,
  smoothCodePinInputBackground: 'white',
  newViewBackGround: '#FF8CAD',
  dashboardIconText: '#FF8CAD',
  isIndigoTheme: false,
  isOrangeTheme: false,
  isDarkTheme: false,
  isLightTheme: false,
  appHeaderColor: '#FF8CAD',
  dashboardBottomTabTex: 'white',
  alertThemeTextColor: '#FF8CAD',

  //header
  headerBackGroundColor: '#FF8CAD',
  headerArrowColor: '#FDBDD0',
  //main
  mainBackGroundColor: '#f3f4f4',
  //textFiled
  textfieldBackgroundColor: 'white',
  textFieldCursor: '#FF8CAD',
  textFieldText: 'black',
  //custom Text Color
  mainTextColors: '#FF8CAD',
  loginBottomNav: '#FF8CAD',
  //Tab Navigate
  tabNavigateBackground: 'white',
  transferReciptDownlaodBtn: '#0d1821',

  tabNavigateTextBackground: '#FF8CAD',
  tabNavigateLeftIcon: '#FF8CAD',
  tabNavigateRightIcon: '#FF8CAD',
  tabNavigateonPress: 'white',
  tabBarColor: 'lightgrey',
  //dashboard
  dashboardHeaderBack: '#FF8CAD',
  dashboardLogoutBtn: '#FDBDD0',
  dashboardSubContainerBack: '#FDBDD0',
  dashboardChildContainerBack: '#FF8CAD',
  dashboardBottomTabView: '#FF8CAD',
  dashboardBottomIcon: 'white',
  dashboardBackGroundColor: 'white',
  textFieldBorderColor: '#cfd1d3',

  modalComponentHeader: '#FF8CAD',
  modalBackGround: 'white',
  alertBackGroundColor: 'white',

  BtnBackground: '#FF8CAD',
  subContainer: 'white',
  silver: 'silver',
  red: 'red',
  whiteColor: 'white',
  primary_green: '#FF8CAD',
  grey: 'grey',
  lightGrey: 'lightgrey',
  icon_color: '#FF8CAD',
  icon_under_coolor: '#FF8CAD',
  header_background: 'white',
  header_left_btn_color: '#FF8CAD',
  overall_view_color: '#FF8CAD',
  //Dashboard
  dash_icon_color: '#FF8CAD',
  //smooth input view
  smoothinpout_color: '#FF8CAD',
  //alert icon_color
  generalIcon: 'black',
  childContainer: '#eceded',
  alet_icon: '#ffe135',
  noteRed: 'red',
  blackColor: 'black',
  themeGreyColor: '#b5b5b5',
  smoothCodeInputTextColor: 'grey',
  orange: 'orange',
  backgroundColor: '#f3f4f4',
  PrimaryBlue: '#0d1821',
  borderColor: '#cfd1d3',
  darkGreen: '#005c31',
  secondaryColor: '#0d1821',
  drawerBackGround: '#f3f4f4',
  secondaryLight: '#252f37',
  secondaryLighter: '#3d464d',
  dashboardIconBack: '#f1f1f2',
  DarkGreen: '#005728',
  greyInfoShow: '#eceded',
  themeGrey: '#cfd1d3',
  labelGrey: '#9ea3a6',
  lightThemeGreen: '#ccebdc',
  lightRedColor: '#ffe6eb',
  redColor: '#ff4d72',
  pink: '#ff6686',
  seaGreen: '#FF8CAD',
  yellow: 'yellow',
};

export const indigoTheme = {
  beneficiaryList: 'white',
  beneficiaryListPressed: 'grey',
  dashboardBalancehider: '#7755C3',
  isPinkTheme: false,
  newViewBackGround: '#321178',
  dashboardIconText: '#321178',
  isIndigoTheme: true,
  isOrangeTheme: false,
  isDarkTheme: false,
  isLightTheme: false,
  appHeaderColor: '#321178',
  dashboardBottomTabTex: 'white',
  alertThemeTextColor: '#321178',
  smoothCodePinInputBackground: 'white',

  //header
  headerBackGroundColor: '#321178',
  headerArrowColor: '#7755C3',
  //main
  mainBackGroundColor: '#f3f4f4',
  //textFiled
  textfieldBackgroundColor: 'white',
  textFieldCursor: '#321178',
  textFieldText: 'black',
  //custom Text Color
  mainTextColors: '#321178',
  loginBottomNav: '#321178',
  //Tab Navigate
  tabNavigateBackground: 'white',
  transferReciptDownlaodBtn: '#0d1821',

  tabNavigateTextBackground: '#321178',
  tabNavigateLeftIcon: '#321178',
  tabNavigateRightIcon: '#321178',
  tabNavigateonPress: 'white',
  tabBarColor: 'lightgrey',
  //dashboard
  dashboardHeaderBack: '#321178',
  dashboardLogoutBtn: '#7755C3',
  dashboardSubContainerBack: '#7755C3',
  dashboardChildContainerBack: '#321178',
  dashboardBottomTabView: '#321178',
  dashboardBottomIcon: 'white',
  dashboardBackGroundColor: 'white',
  textFieldBorderColor: '#cfd1d3',

  modalComponentHeader: '#321178',
  modalBackGround: 'white',
  alertBackGroundColor: 'white',

  BtnBackground: '#321178',
  subContainer: 'white',
  silver: 'silver',
  red: 'red',
  whiteColor: 'white',
  primary_green: '#321178',
  grey: 'grey',
  lightGrey: 'lightgrey',
  icon_color: '#321178',
  icon_under_coolor: '#321178',
  header_background: 'white',
  header_left_btn_color: '#321178',
  overall_view_color: '#321178',
  //Dashboard
  dash_icon_color: '#321178',
  //smooth input view
  smoothinpout_color: '#321178',
  //alert icon_color
  generalIcon: 'black',
  childContainer: '#eceded',
  alet_icon: '#ffe135',
  noteRed: 'red',
  blackColor: 'black',
  themeGreyColor: '#b5b5b5',
  smoothCodeInputTextColor: 'grey',
  orange: 'orange',
  backgroundColor: '#f3f4f4',
  PrimaryBlue: '#0d1821',
  borderColor: '#cfd1d3',
  darkGreen: '#005c31',
  secondaryColor: '#0d1821',
  drawerBackGround: '#f3f4f4',
  secondaryLight: '#252f37',
  secondaryLighter: '#3d464d',
  dashboardIconBack: '#f1f1f2',
  DarkGreen: '#005728',
  greyInfoShow: '#eceded',
  themeGrey: '#cfd1d3',
  labelGrey: '#9ea3a6',
  lightThemeGreen: '#ccebdc',
  lightRedColor: '#ffe6eb',
  redColor: '#ff4d72',
  pink: '#ff6686',
  seaGreen: '#321178',
  yellow: 'yellow',
};
export const orangeTheme = {
  beneficiaryList: 'white',
  beneficiaryListPressed: 'grey',
  dashboardBalancehider: '#FFC470',
  isPinkTheme: false,
  isIndigoTheme: false,
  smoothCodePinInputBackground: 'white',
  newViewBackGround: '#FE9601',
  dashboardIconText: '#FE9601',
  isOrangeTheme: true,
  isDarkTheme: false,
  isLightTheme: false,
  appHeaderColor: '#FE9601',
  dashboardBottomTabTex: 'white',
  alertThemeTextColor: '#FE9601',

  //header
  headerBackGroundColor: '#FE9601',
  headerArrowColor: '#FFC470',
  //main
  mainBackGroundColor: '#f3f4f4',
  //textFiled
  textfieldBackgroundColor: 'white',
  textFieldCursor: '#FE9601',
  textFieldText: 'black',
  //custom Text Color
  mainTextColors: '#FE9601',
  loginBottomNav: '#FE9601',
  //Tab Navigate
  tabNavigateBackground: 'white',
  transferReciptDownlaodBtn: '#0d1821',

  tabNavigateTextBackground: '#FE9601',
  tabNavigateLeftIcon: '#FE9601',
  tabNavigateRightIcon: '#FE9601',
  tabNavigateonPress: 'white',
  tabBarColor: 'lightgrey',
  //dashboard
  dashboardHeaderBack: '#FE9601',
  dashboardLogoutBtn: '#FFC470',
  dashboardSubContainerBack: '#FFC470',
  dashboardChildContainerBack: '#FE9601',
  dashboardBottomTabView: '#FE9601',
  dashboardBottomIcon: 'white',
  dashboardBackGroundColor: 'white',
  textFieldBorderColor: '#cfd1d3',

  modalComponentHeader: '#FE9601',
  modalBackGround: 'white',
  alertBackGroundColor: 'white',

  BtnBackground: '#FE9601',
  subContainer: 'white',
  silver: 'silver',
  red: 'red',
  whiteColor: 'white',
  primary_green: '#FE9601',
  grey: 'grey',
  lightGrey: 'lightgrey',
  icon_color: '#FE9601',
  icon_under_coolor: '#FE9601',
  header_background: 'white',
  header_left_btn_color: '#FE9601',
  overall_view_color: '#FE9601',
  //Dashboard
  dash_icon_color: '#FE9601',
  //smooth input view
  smoothinpout_color: '#FE9601',
  //alert icon_color
  generalIcon: 'black',
  childContainer: '#eceded',
  alet_icon: '#ffe135',
  noteRed: 'red',
  blackColor: 'black',
  themeGreyColor: '#b5b5b5',
  smoothCodeInputTextColor: 'grey',
  orange: 'orange',
  backgroundColor: '#f3f4f4',
  PrimaryBlue: '#0d1821',
  borderColor: '#cfd1d3',
  darkGreen: '#005c31',
  secondaryColor: '#0d1821',
  drawerBackGround: '#f3f4f4',
  secondaryLight: '#252f37',
  secondaryLighter: '#3d464d',
  dashboardIconBack: '#f1f1f2',
  DarkGreen: '#005728',
  greyInfoShow: '#eceded',
  themeGrey: '#cfd1d3',
  labelGrey: '#9ea3a6',
  lightThemeGreen: '#ccebdc',
  lightRedColor: '#ffe6eb',
  redColor: '#ff4d72',
  pink: '#ff6686',
  seaGreen: '#FE9601',
  yellow: 'yellow',
};
